spring:
  application:
    name: aps-engine
  jackson:
    deserialization:
      adjust-dates-to-context-time-zone: false
  servlet:
    multipart:
      max-file-size: 4MB
      max-request-size: 4MB
  jpa:
    open-in-view: false
    properties:
      hibernate:
        generate_statistics: ${APS_HIBERNATE_STATISTICS:false}

management:
  endpoints:
    web:
      exposure:
        include: health,metrics
