CREATE TABLE changeover_time (
    changeover_time_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    machine_id BIGINT NOT NULL,
    from_product_id BIGINT NOT NULL,
    to_product_id BIGINT NOT NULL,
    changeover_minutes INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_changeover_time PRIMARY KEY (changeover_time_id),
    CONSTRAINT fk_changeover_time_machine FOREIGN KEY (machine_id)
        REFERENCES machine (machine_id),
    CONSTRAINT fk_changeover_time_from_product FOREIGN KEY (from_product_id)
        REFERENCES product (product_id),
    CONSTRAINT fk_changeover_time_to_product FOREIGN KEY (to_product_id)
        REFERENCES product (product_id),
    CONSTRAINT uk_changeover_time_machine_products UNIQUE (
        machine_id,
        from_product_id,
        to_product_id
    ),
    CONSTRAINT ck_changeover_time_different_products CHECK (
        from_product_id <> to_product_id
    ),
    CONSTRAINT ck_changeover_time_minutes CHECK (
        changeover_minutes >= 0
    )
);

CREATE INDEX ix_changeover_time_machine_id
    ON changeover_time (machine_id);

CREATE INDEX ix_changeover_time_product_pair
    ON changeover_time (from_product_id, to_product_id);
