CREATE EXTENSION IF NOT EXISTS btree_gist;

CREATE TABLE machine_maintenance (
    machine_maintenance_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    machine_id BIGINT NOT NULL,
    start_at TIMESTAMP WITH TIME ZONE NOT NULL,
    end_at TIMESTAMP WITH TIME ZONE NOT NULL,
    maintenance_reason VARCHAR(200) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_machine_maintenance
        PRIMARY KEY (machine_maintenance_id),
    CONSTRAINT fk_machine_maintenance_machine
        FOREIGN KEY (machine_id) REFERENCES machine (machine_id),
    CONSTRAINT ck_machine_maintenance_period CHECK (end_at > start_at),
    CONSTRAINT ck_machine_maintenance_reason_not_blank CHECK (
        btrim(maintenance_reason) <> ''
    ),
    CONSTRAINT ex_machine_maintenance_no_overlap
        EXCLUDE USING GIST (
            machine_id WITH =,
            tstzrange(start_at, end_at, '[)') WITH &&
        ) WHERE (active)
);

CREATE INDEX ix_machine_maintenance_machine_start
    ON machine_maintenance (machine_id, start_at);
