CREATE TABLE operation_machine_candidate (
    operation_machine_candidate_id BIGINT
        GENERATED BY DEFAULT AS IDENTITY,
    operation_id BIGINT NOT NULL,
    machine_id BIGINT NOT NULL,
    candidate_priority INTEGER NOT NULL,
    CONSTRAINT pk_operation_machine_candidate
        PRIMARY KEY (operation_machine_candidate_id),
    CONSTRAINT fk_operation_machine_candidate_operation
        FOREIGN KEY (operation_id)
            REFERENCES operation (operation_id),
    CONSTRAINT fk_operation_machine_candidate_machine
        FOREIGN KEY (machine_id)
            REFERENCES machine (machine_id),
    CONSTRAINT uk_operation_machine_candidate
        UNIQUE (operation_id, machine_id),
    CONSTRAINT ck_operation_machine_candidate_priority
        CHECK (candidate_priority BETWEEN 1 AND 1000)
);

CREATE INDEX ix_operation_machine_candidate_operation_priority
    ON operation_machine_candidate (
        operation_id,
        candidate_priority,
        operation_machine_candidate_id
    );

CREATE INDEX ix_operation_machine_candidate_machine_id
    ON operation_machine_candidate (machine_id);

INSERT INTO operation_machine_candidate (
    operation_id,
    machine_id,
    candidate_priority
)
SELECT
    operation_id,
    machine_id,
    1
FROM operation;
