CREATE TABLE planning_data_import_run (
    planning_data_import_run_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    request_key UUID NOT NULL,
    file_name VARCHAR(255) NOT NULL,
    file_sha256 VARCHAR(64) NOT NULL,
    total_rows INTEGER NOT NULL,
    success_rows INTEGER NOT NULL DEFAULT 0,
    failed_rows INTEGER NOT NULL DEFAULT 0,
    retry_count INTEGER NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE NOT NULL,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_planning_data_import_run
        PRIMARY KEY (planning_data_import_run_id),
    CONSTRAINT uk_planning_data_import_request_key UNIQUE (request_key),
    CONSTRAINT ck_planning_data_import_hash CHECK (
        file_sha256 ~ '^[0-9a-f]{64}$'
    ),
    CONSTRAINT ck_planning_data_import_counts CHECK (
        total_rows BETWEEN 1 AND 2000
        AND success_rows BETWEEN 0 AND total_rows
        AND failed_rows BETWEEN 0 AND total_rows
        AND retry_count >= 0
    ),
    CONSTRAINT ck_planning_data_import_status CHECK (
        status IN ('RUNNING', 'COMPLETED', 'FAILED', 'INTERRUPTED')
    )
);

CREATE TABLE planning_data_import_row (
    planning_data_import_row_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    planning_data_import_run_id BIGINT NOT NULL,
    row_number INTEGER NOT NULL,
    data_type VARCHAR(30),
    status VARCHAR(20) NOT NULL,
    CONSTRAINT pk_planning_data_import_row
        PRIMARY KEY (planning_data_import_row_id),
    CONSTRAINT fk_planning_data_import_row_run
        FOREIGN KEY (planning_data_import_run_id)
        REFERENCES planning_data_import_run (planning_data_import_run_id)
        ON DELETE CASCADE,
    CONSTRAINT uk_planning_data_import_row_number UNIQUE (
        planning_data_import_run_id,
        row_number
    ),
    CONSTRAINT ck_planning_data_import_row_number CHECK (row_number >= 2),
    CONSTRAINT ck_planning_data_import_row_type CHECK (
        data_type IS NULL
        OR data_type IN (
            'FACTORY',
            'PRODUCTION_LINE',
            'MACHINE',
            'PRODUCT',
            'ROUTING',
            'PRODUCTION_ORDER'
        )
    ),
    CONSTRAINT ck_planning_data_import_row_status CHECK (
        status IN ('SUCCEEDED', 'FAILED', 'SKIPPED')
    )
);

CREATE TABLE planning_data_import_row_error (
    planning_data_import_row_error_id
        BIGINT GENERATED BY DEFAULT AS IDENTITY,
    planning_data_import_row_id BIGINT NOT NULL,
    error_field VARCHAR(50) NOT NULL,
    error_code VARCHAR(50) NOT NULL,
    error_message VARCHAR(500) NOT NULL,
    CONSTRAINT pk_planning_data_import_row_error
        PRIMARY KEY (planning_data_import_row_error_id),
    CONSTRAINT fk_planning_data_import_error_row
        FOREIGN KEY (planning_data_import_row_id)
        REFERENCES planning_data_import_row (planning_data_import_row_id)
        ON DELETE CASCADE
);

CREATE INDEX ix_planning_data_import_status
    ON planning_data_import_run (status, created_at);
CREATE INDEX ix_planning_data_import_row_run
    ON planning_data_import_row (planning_data_import_run_id, row_number);
CREATE INDEX ix_planning_data_import_error_row
    ON planning_data_import_row_error (planning_data_import_row_id);
