CREATE TABLE schedule_execution (
    schedule_execution_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    execution_key UUID NOT NULL,
    planning_start TIMESTAMP WITH TIME ZONE NOT NULL,
    planning_offset_seconds INTEGER NOT NULL,
    dispatching_rule VARCHAR(30) NOT NULL,
    source_schedule_run_id BIGINT,
    frozen_at TIMESTAMP WITH TIME ZONE,
    result_schedule_run_id BIGINT,
    status VARCHAR(20) NOT NULL,
    failure_reason VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    started_at TIMESTAMP WITH TIME ZONE,
    completed_at TIMESTAMP WITH TIME ZONE,
    CONSTRAINT pk_schedule_execution
        PRIMARY KEY (schedule_execution_id),
    CONSTRAINT uk_schedule_execution_key UNIQUE (execution_key),
    CONSTRAINT uk_schedule_execution_result UNIQUE (result_schedule_run_id),
    CONSTRAINT fk_schedule_execution_source
        FOREIGN KEY (source_schedule_run_id)
        REFERENCES schedule_run (schedule_run_id)
        ON DELETE RESTRICT,
    CONSTRAINT fk_schedule_execution_result
        FOREIGN KEY (result_schedule_run_id)
        REFERENCES schedule_run (schedule_run_id)
        ON DELETE RESTRICT,
    CONSTRAINT ck_schedule_execution_rule CHECK (
        dispatching_rule IN ('EXPLICIT_PRIORITY', 'EDD', 'SPT')
    ),
    CONSTRAINT ck_schedule_execution_planning_offset CHECK (
        planning_offset_seconds BETWEEN -64800 AND 64800
    ),
    CONSTRAINT ck_schedule_execution_trace CHECK (
        (source_schedule_run_id IS NULL AND frozen_at IS NULL)
        OR (
            source_schedule_run_id IS NOT NULL
            AND frozen_at IS NOT NULL
            AND frozen_at >= planning_start
        )
    ),
    CONSTRAINT ck_schedule_execution_status CHECK (
        status IN ('QUEUED', 'RUNNING', 'COMPLETED', 'FAILED')
    ),
    CONSTRAINT ck_schedule_execution_lifecycle CHECK (
        (
            status = 'QUEUED'
            AND started_at IS NULL
            AND completed_at IS NULL
            AND result_schedule_run_id IS NULL
            AND failure_reason IS NULL
        )
        OR (
            status = 'RUNNING'
            AND started_at IS NOT NULL
            AND completed_at IS NULL
            AND result_schedule_run_id IS NULL
            AND failure_reason IS NULL
        )
        OR (
            status = 'COMPLETED'
            AND started_at IS NOT NULL
            AND completed_at IS NOT NULL
            AND result_schedule_run_id IS NOT NULL
            AND failure_reason IS NULL
        )
        OR (
            status = 'FAILED'
            AND completed_at IS NOT NULL
            AND result_schedule_run_id IS NULL
            AND failure_reason IS NOT NULL
        )
    )
);

CREATE INDEX ix_schedule_execution_status_created
    ON schedule_execution (status, created_at, schedule_execution_id);
CREATE INDEX ix_schedule_execution_created
    ON schedule_execution (created_at DESC, schedule_execution_id DESC);
CREATE INDEX ix_schedule_execution_source
    ON schedule_execution (source_schedule_run_id);
