CREATE TABLE factory
(
    factory_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    factory_code VARCHAR(50)  NOT NULL,
    factory_name VARCHAR(100) NOT NULL,
    active       BOOLEAN      NOT NULL,
    CONSTRAINT pk_factory PRIMARY KEY (factory_id),
    CONSTRAINT uk_factory_code UNIQUE (factory_code),
    CONSTRAINT ck_factory_code_format CHECK (
        factory_code ~ '^[A-Z0-9][A-Z0-9_-]{0,49}$'
    ),
    CONSTRAINT ck_factory_name_not_blank CHECK (
        btrim(factory_name) <> ''
    )
);

