CREATE TABLE production_line
(
    production_line_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    factory_id         BIGINT       NOT NULL,
    line_code          VARCHAR(50)  NOT NULL,
    line_name          VARCHAR(100) NOT NULL,
    active             BOOLEAN      NOT NULL,
    CONSTRAINT pk_production_line PRIMARY KEY (production_line_id),
    CONSTRAINT fk_production_line_factory
        FOREIGN KEY (factory_id) REFERENCES factory (factory_id),
    CONSTRAINT uk_production_line_factory_code
        UNIQUE (factory_id, line_code),
    CONSTRAINT ck_production_line_code_format CHECK (
        line_code ~ '^[A-Z0-9][A-Z0-9_-]{0,49}$'
    ),
    CONSTRAINT ck_production_line_name_not_blank CHECK (
        btrim(line_name) <> ''
    )
);

CREATE INDEX ix_production_line_factory_id
    ON production_line (factory_id);

