CREATE TABLE machine
(
    machine_id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
    production_line_id BIGINT       NOT NULL,
    machine_code       VARCHAR(50)  NOT NULL,
    machine_name       VARCHAR(100) NOT NULL,
    status             VARCHAR(20)  NOT NULL,
    CONSTRAINT pk_machine PRIMARY KEY (machine_id),
    CONSTRAINT fk_machine_production_line
        FOREIGN KEY (production_line_id)
            REFERENCES production_line (production_line_id),
    CONSTRAINT uk_machine_line_code
        UNIQUE (production_line_id, machine_code),
    CONSTRAINT ck_machine_code_format CHECK (
        machine_code ~ '^[A-Z0-9][A-Z0-9_-]{0,49}$'
    ),
    CONSTRAINT ck_machine_name_not_blank CHECK (
        btrim(machine_name) <> ''
    ),
    CONSTRAINT ck_machine_status CHECK (
        status IN ('AVAILABLE', 'STOPPED', 'INACTIVE')
    )
);

CREATE INDEX ix_machine_production_line_id
    ON machine (production_line_id);

