CREATE TABLE product (
    product_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_code VARCHAR(50) NOT NULL,
    product_name VARCHAR(100) NOT NULL,
    unit VARCHAR(20) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_product PRIMARY KEY (product_id),
    CONSTRAINT uk_product_code UNIQUE (product_code),
    CONSTRAINT ck_product_code_format CHECK (
        product_code ~ '^[A-Z0-9][A-Z0-9_-]*$'
    ),
    CONSTRAINT ck_product_name_not_blank CHECK (
        LENGTH(BTRIM(product_name)) > 0
    ),
    CONSTRAINT ck_product_unit CHECK (
        unit IN ('PIECE', 'KILOGRAM', 'METER')
    )
);
