CREATE TABLE routing (
    routing_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    product_id BIGINT NOT NULL,
    routing_code VARCHAR(50) NOT NULL,
    routing_name VARCHAR(100) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_routing PRIMARY KEY (routing_id),
    CONSTRAINT fk_routing_product FOREIGN KEY (product_id)
        REFERENCES product (product_id),
    CONSTRAINT uk_routing_product_code UNIQUE (product_id, routing_code),
    CONSTRAINT ck_routing_code_format CHECK (
        routing_code ~ '^[A-Z0-9][A-Z0-9_-]*$'
    ),
    CONSTRAINT ck_routing_name_not_blank CHECK (
        LENGTH(BTRIM(routing_name)) > 0
    )
);

CREATE INDEX ix_routing_product_id ON routing (product_id);

CREATE TABLE operation (
    operation_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    routing_id BIGINT NOT NULL,
    machine_id BIGINT NOT NULL,
    operation_sequence INTEGER NOT NULL,
    operation_code VARCHAR(50) NOT NULL,
    operation_name VARCHAR(100) NOT NULL,
    processing_time_minutes INTEGER NOT NULL,
    CONSTRAINT pk_operation PRIMARY KEY (operation_id),
    CONSTRAINT fk_operation_routing FOREIGN KEY (routing_id)
        REFERENCES routing (routing_id),
    CONSTRAINT fk_operation_machine FOREIGN KEY (machine_id)
        REFERENCES machine (machine_id),
    CONSTRAINT uk_operation_routing_sequence UNIQUE (
        routing_id,
        operation_sequence
    ),
    CONSTRAINT uk_operation_routing_code UNIQUE (
        routing_id,
        operation_code
    ),
    CONSTRAINT ck_operation_sequence CHECK (operation_sequence >= 1),
    CONSTRAINT ck_operation_code_format CHECK (
        operation_code ~ '^[A-Z0-9][A-Z0-9_-]*$'
    ),
    CONSTRAINT ck_operation_name_not_blank CHECK (
        LENGTH(BTRIM(operation_name)) > 0
    ),
    CONSTRAINT ck_operation_processing_time CHECK (
        processing_time_minutes BETWEEN 1 AND 10080
    )
);

CREATE INDEX ix_operation_routing_id ON operation (routing_id);
CREATE INDEX ix_operation_machine_id ON operation (machine_id);
