CREATE TABLE production_order (
    production_order_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    routing_id BIGINT NOT NULL,
    order_number VARCHAR(50) NOT NULL,
    quantity BIGINT NOT NULL,
    release_at TIMESTAMP WITH TIME ZONE NOT NULL,
    due_at TIMESTAMP WITH TIME ZONE NOT NULL,
    priority INTEGER NOT NULL,
    status VARCHAR(20) NOT NULL,
    CONSTRAINT pk_production_order PRIMARY KEY (production_order_id),
    CONSTRAINT fk_production_order_routing FOREIGN KEY (routing_id)
        REFERENCES routing (routing_id),
    CONSTRAINT uk_production_order_number UNIQUE (order_number),
    CONSTRAINT ck_production_order_number_format CHECK (
        order_number ~ '^[A-Z0-9][A-Z0-9_-]*$'
    ),
    CONSTRAINT ck_production_order_quantity CHECK (
        quantity BETWEEN 1 AND 1000000
    ),
    CONSTRAINT ck_production_order_dates CHECK (due_at > release_at),
    CONSTRAINT ck_production_order_priority CHECK (
        priority BETWEEN 1 AND 100
    ),
    CONSTRAINT ck_production_order_status CHECK (
        status IN ('DRAFT', 'CONFIRMED', 'SCHEDULED', 'CANCELLED')
    )
);

CREATE INDEX ix_production_order_routing_id
    ON production_order (routing_id);
CREATE INDEX ix_production_order_status_due
    ON production_order (status, due_at);
