CREATE TABLE working_calendar (
    working_calendar_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    machine_id BIGINT NOT NULL,
    day_of_week VARCHAR(9) NOT NULL,
    start_time TIME NOT NULL,
    end_time TIME NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT pk_working_calendar PRIMARY KEY (working_calendar_id),
    CONSTRAINT fk_working_calendar_machine FOREIGN KEY (machine_id)
        REFERENCES machine (machine_id),
    CONSTRAINT uk_working_calendar_machine_window UNIQUE (
        machine_id,
        day_of_week,
        start_time,
        end_time
    ),
    CONSTRAINT ck_working_calendar_day CHECK (
        day_of_week IN (
            'MONDAY',
            'TUESDAY',
            'WEDNESDAY',
            'THURSDAY',
            'FRIDAY',
            'SATURDAY',
            'SUNDAY'
        )
    ),
    CONSTRAINT ck_working_calendar_time CHECK (end_time > start_time)
);

CREATE INDEX ix_working_calendar_machine_day
    ON working_calendar (machine_id, day_of_week, start_time);
